version: "3.2"

services:
  menu_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: menu_api
    image: menu_api:${VERSION:-latest}
    restart: always

    volumes:
      - .:/app
    ports:
      - "9999:8000"
#    env_file:
#      - .env
    networks:
      - menu_net

networks:
  menu_net:
