version: "3.8"

services:
  menu_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: menu_api
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: >
      sh -c " alembic upgrade head &&
             python3 data_migrations/menu_migration.py
    env_file:
      - .env
    networks:
      - menu_net
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data

volumes:
  pg:
    driver: local
