version: "3.8"

services:
  menu_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: menu_api
    restart: always
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: >
      sh -c "alembic upgrade head &&
              uvicorn app.instances:app --host 0.0.0.0 &&
              python3 data_migrations/menu_migration.py"
    networks:
      - custom
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    ports:
      - 5434:5432
    volumes:
      - pg:/var/lib/postgresql
    networks:
      - custom

volumes:
  pg:
    driver: local

networks:
  custom:
    driver: bridge