version: "3.2"

services:
  menu_api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: menu_api
    image: menu_api:${VERSION:-latest}
    restart: always
    volumes:
      - .:/app
    ports:
      - ${APP_EXPOSED_PORT}:8000
    env_file:
      - .env
    networks:
      - menu_net
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    restart: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - .:/var/lib/postgresql/data

volumes:
  pg:
    driver: local
